version: '3.8'

services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./Criador/nginx
    ports:
      - "3050:80"

  api:
    container_name: criador-api
    build:
      dockerfile: Dockerfile
      context: "./Criador/server"
    volumes:
      - /app/node_modules
      - ./Criador/server:/app
    env_file:
      - ./config/app.config
    
  client:
    container_name: criador-react
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./Criador/client
    volumes:
      - /app/node_modules
      - ./Criador/client:/app
