name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    env:
      PORT: "${{ secrets.PORT }}"
      DB_CONNECT: "${{ secrets.DB_CONNECT }}"

    steps:  
      - name: Create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_CONNECT=${{ secrets.DB_CONNECT }} >> .env
          cat .env
        

      - name: Export the env variables
        run: |
          export PORT="${{ secrets.PORT }}"
          export DB_CONNECT="${{ secrets.DB_CONNECT }}"

      - name: Build and deploy
        run: |
          echo "PORT=${{secrets.PORT}}"
          echo "DB_CONNECT=${{secrets.DB_CONNECT}}"

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: osmosian/criador           
          
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc        
        with:
          context: ./server
          push: true
          tags: osmosian/criador:v1.0.0
          labels: ${{ steps.meta.outputs.labels }}        
